apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.10
  - resources/namespace.yaml

patches:
  - path: patches/argocd-cm.yaml
  # - path: patches/argocd-rbac-cm.yaml
