apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: my-simple-golang
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zooeymoon1989/tmp-argocd-study.git
    targetRevision: HEAD
    path: ch02/dev
  destination:
    namespace: simple-golang
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true