apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd


# Warning: 'bases' is deprecated.
# Please use 'resources' instead.

# bases:
#   - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.1.1

resources:
  - resources/namespace.yaml
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.1.1

# Warning: 'patchesStrategicMerge' is deprecated.
#Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.

patchesStrategicMerge:
  - patches/argocd-cm.yaml
  - patches/argocd-server-deployment.ya``ml
  - patches/argocd-repo-server-deployment.yaml
  - patches/argocd-application-controller-statefulset.yaml
